# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: my-vars

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6

  - script: 'python -m pip install --upgrade -r ./env-create/requirements.txt' 
    displayName: 'Pip Installs'

  - script: 'python ./aml/workspace.py --ws $(workspace) --id $(subscriptionId) --group $(resourceGroup)' 
    displayName: 'Get Workspace'
